name: Build and Deploy to AWS
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy-production:
    name: Deploy(Production)
    runs-on: ubuntu-latest
    environment: Recruit-Production
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_VARS }}" >> .env
      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: mkdir -p ~/srv/ubuntu

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: ~/srv/ubuntu/
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 10022 # SSH í¬íŠ¸ë¥¼ ì—¬ê¸°ì— ì§€ì •í•˜ì„¸ìš”.
          script_start: |
            cd ~/econo-recruit/server # ì›í•˜ëŠ” ê²½ë¡œë¡œ ë³€ê²½í•˜ì„¸ìš”.
          script: |
            sh docker-install.sh
            echo "start docker-compose up: econovation-server"
            sudo docker-compose -v
            cat .env 
            sudo docker-compose -f docker-compose.yml pull
            sudo docker-compose -f docker-compose.yml --env-file .env up --build -d 
            echo "prune images"
            sudo docker system prune --all -f
      - name: Notify on success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: '#703CDE'
          SLACK_USERNAME: ì„œí˜„ì´ì˜ ë°°í¬ìš”ì •
#          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Message
          SLACK_MESSAGE: "ì„œë²„ Build succeeded ğŸ‰ \n\n *CommitMessage* \n ${{ join(github.event.commits.*.message, '\n') }}"
      - name: Notify on failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: '#F33D63'
          SLACK_USERNAME: ì„œí˜„ì´ì˜ ë°°í¬ìš”ì •
#          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Message
          SLACK_MESSAGE: "ì„œë²„ Build failed ğŸ¥² \n\n *CommitMessage* \n ${{ join(github.event.commits.*.message, '\n') }}"